<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>name</key>
		<string>Papyrus Compiled</string>
		<key>scopeName</key>
		<string>source.papyrus-compiled</string>
		<key>fileTypes</key>
		<array>
			<string>pex</string>
		</array>
		<key>uuid</key>
		<string>23d8c729-aa50-4521-8b92-b2e75fc58f4a</string>
		<key>patterns</key>
		<array>
		</array>
	</dict>
</plist>
